dist: bionic

language: go

go:
- 1.15.x

services:
- docker

after_success:
- bash <(curl -s https://codecov.io/bash)

script:
  - go test -run Libcode -race -coverprofile=coverage.txt -covermode=atomic
  - go build
  - go test -run Libcode

jobs:
  include:
  - stage: Build, Unit-Tests & Fuzz-Tests
    go: 1.14.x
    script:
    - "./fuzzit.sh local-regression"
  - stage: Fuzzit (Fuzzing)
    if: branch = master AND type IN (push)
    go: 1.14.x
    script:
    - "./fuzzit.sh fuzzing"

env:
  global:
    secure: i1zbaX5Pb/ZI+Dq18+A2dO195L2GJ7hhDFEZjqtiQTxNy6LITqT/zpncG3Em79R5XLfxYc0Rg6mx5wbwi43olJXRY6cTaFwYSt9hgF9u26DNfxt32RNlG/rPbYdecVPwK5YKGOoIZFVZ5ZRXlADdWeg1RusMRTZTs0EbxHSLmN81mJm40JlNAsUQRAzdhXAzZCsxT5c9UXwJTATi4rqbxyqA0fs+95eEQFeMr5Q5gzD0WzO3PRBdqB9BwS9E/vTp6RE/IfNfZjUd641MMR7ZmaAjFszTp57rP6ndNBy7vAOTON7dYT8NXGAObRTDgmc0KqvIyh6z6lwSTA4SYwVbRPF0Mql+nEaJ0kEZ6vpLSoOgEjuoeAGjDp0B4WHVZt9ISBvHV5X8ETC6WhTvClNymMg6lAcOSA6KvPFUUWZlkymawJzg2qCMEhlR62VlpAkg2bmluzb9/AP57R0jqp/UteugzT7zAR3/1Dpah0zpAGiLgOVBurTvd9hDbR+QsfrG9nJmzXhgoNVr7VBLNSzxMtt4IAb6VATF5g5sD4lSS/FGq1ZtIBYL4rLFapIPeTLdxKZkD04gOPJ86+ndtmxWD0z88rIS2/HynasbTMvQWtQOR8gwBzjXnF3N1RoKfbY2aQcEgZwD41WJ7WDHISL2BRFylzCwvOCT7ws0x246jYg=
