dist: bionic
language: go
go:
    - 1.12.x
services:
    - docker
env:
  global:
    secure: YnPUCdfYJvln7KIEVrOIRMwuEdDK+yCa3ySotWcshSsnkCiAv8DUvUJMWCL9fsB9z7izcmI407wlFavh797SnmIRHR+/1op4HTNMTZ+0oSaZZBM9GtWf1dMKwEo4P2eBfcI2BimmCZDIWlTHg3S4yHxc6a737J/sYIcGpePeu2MgoXeatKyCiW5h34p3IebqnUkkJILpIXTe89pv8GFjcCS5tSfmMELohZk9JiT3wqcVuiLcSdYHDgsmU9Ukf3na58RyDMe7gZDPAO6G+3R7aESU9+WYTAgrZGIZoaJmD61s0RRTZ6nVDssGXkY6HIo8GfiCwK6APki2qzv1VuZV/lyp/GENqRAaDxBT4qyO5ZusvDpPKC6gH0uKmJwZtgwjURXMc5Bj7hjPztkBNF9D0nPts8zI+xkieroYTst9pz1lW8G7c2yoAYmbtNFxp9QvWqFtWKYdiyTFuoSGNHxXXhH8lJtxB+NSh34FUAfXIjzGOdQ6RkLhUxLELKB/h1RGScy1Cl4rVUrpLp2kuFPN24WDXDDC2431XzQGyEZOBNe+o+zkljan49JPAl1/sz0nwzOORNHJ68LyGyqWhiBm/S0+HNM6Hd24jXMJp0IcXaNgCRGhUGn8BH/GZiCP2vSokEPGrnqb6Qc8NFXR5PPouuKNXr0kSprUlf7pVwd9jto=
jobs:
  include:
  - stage: Build, Unit-Tests & Fuzz-Tests
    go: 1.14.x
    script:
    - "./fuzzit.sh local-regression"
  - stage: Fuzzit (Fuzzing)
    if: branch = master AND type IN (push)
    go: 1.14.x
    script:
    - "./fuzzit.sh fuzzing"
